# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build-test-lint
run-name: Build, test and lint by ${{ github.actor }}, PR ${{ github.ref }}

env:
  GH_WORKFLOW_TARGET: foresight

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        check-latest: true
        # Enable dependency caching
        cache: "pip"
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install development dependencies if they exist.
        if grep -q "all = \[" pyproject.toml; then
            pip install -e '.[all]'
        else
            pip install -e .
        fi
        pip install pylint pytest
    - name: Run all tests (except integration tests)
      run: |
        pytest --ignore-glob "*integration_test.py" $GH_WORKFLOW_TARGET
    - name: Run linter
      run: |
        pylint $GH_WORKFLOW_TARGET
